[build]
  publish = "dist/proyecto-muni-frontend"
  command = "npm install --force && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18.18.0"
  NPM_FLAGS = "--force"

# Configuración de cache para mejor rendimiento
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000" 