[build]
  publish = "dist/proyecto-muni-frontend"
  command = "node -v && npm install --legacy-peer-deps && NODE_OPTIONS=--max_old_space_size=4096 npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18.19.1"
  NPM_VERSION = "8.19.4"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_OPTIONS = "--max_old_space_size=4096"

# Configuración de cache para mejor rendimiento
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000" 